### ISSUE TITLE
onFragment breaks is both `on` and `target` properties are null

### ISSUE THREAD

**Issue by PonteIneptique** [IIIF-Commons/manifesto#121]
https://github.com/IIIF-Commons/manifesto/blob/72046aa7a901c0bfabe51c73598405ff76b73623/src/Canvas.ts#L370-L373

Line 371 expect both to be well formed, I would recommend inserting a line 

```js
if (!on || !target) { return undefined; }
```
which would act as a safe-keeper. 

I am using https://github.com/dbmdz/mirador-textoverlay and this seems to be provoked by a bad line in my ALTO (I suppose ?), but it still feel like some safety here would avoid a complete throw.

**Comment by PonteIneptique** [comment]
@stephenwf Thanks for the quick merge. Is it possible to release this as a bugfix ? :)

**Comment by stephenwf** [comment]
Yes, should be in v4.2.17 shortly 👍
