### ISSUE TITLE
getViewingDirection() doesn't work for Collections

### ISSUE THREAD

**Issue by sdellis** [IIIF-Commons/manifesto#31]
Perhaps I'm doing it wrong, but I can get a viewing direction on a manifest with the `getViewingDirection()` method, but I can't do the same on a Collection. Viewing direction on Collections is a [Prezi 3.0 feature](http://prezi3.iiif.io/api/presentation/3.0/#viewingdirection), along with Sequences and Ranges.

**Comment by edsilv** [comment]
Have added `getViewingDirection` to v2.2.8 and published to npm.
