### ISSUE TITLE
use fetch for requests

### ISSUE THREAD

**Issue by damooo** [IIIF-Commons/manifesto#55]
umd bundle, with out minification is of size nearly 350k, and 80% of that is node js shims, for http, request, streams, buffers, urls, so on.. which are bloat for browser side. hence following proposal:

- use fetch for all network requests. it has powerful promice based api built into browsers, and have very good support across browsers. and it handles both http, and https with same interface
- on node use node-fetch, which provides full api compatability with browser fetch.
- we can easily have some 30 lines wrapper around them for uniform handle, and keep them out from bundling, thus both node and browser can be supported. we used this method in our apps in production. We used rollup for bundling, which is much powerful for library bundling.

it seems only Util.js performs networking.. if it is ok, i will try to create a PR with those changes.

**Comment by edsilv** [comment]
Sounds great! Looking forward to the PR

**Comment by edsilv** [comment]
We've talked about using https://www.npmjs.com/package/isomorphic-fetch before which looks like a good option cc @stephen @mejackreed

**Comment by damooo** [comment]
isomorphic fetch adds fetch binding as global on both node and browser, and implements fetch wrapper api instead of just fallbacking, which still adds considerable size. instead we can easily import nodeFetch itself and fallback to it, with out adding it to bundle.. rollup supports this for umd bundles.

i created a 2k package few days back for our use: https://www.npmjs.com/package/vedavaapi-web we can use it as follows:
```js
const web = require('vedavaapi-web');
// it provides following isomorphic web apis. on browser, proxies to browser builtins, on node uses appropriate compatible ones listed in dependencies
const { fetch, URL, URLSearchParams, Headers, request } = web;
// use above as normal
fetch('http://www.google.com", {method: 'GET'}
```
it handles cokkies properly on node using `tough-cookie`, as node-fetch by default doesn't support cookies.
it also provides `request`, which will handle fetch errors properly, and dserializes to corresponding body types, as fetch by default doesn't raises error for http errors. we can embed same code in this or use package as dependency.
